# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=160)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('degree', models.CharField(choices=[('', 'Сонгох'), ('burendund', 'Бүрэн дунд'), ('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('doctor', 'Доктор'), ('academich', 'Академич'), ('profeccor', 'Профессор')], default='Сонгох', max_length=16)),
                ('number', models.CharField(max_length=20)),
                ('copy', models.FileField(blank=True, null=True, upload_to='')),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='application.General')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='application.General')),
            ],
            options={
                'db_table': 'experience',
            },
        ),
    ]
