# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_education_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=160)),
            ],
        ),
        migrations.AddField(
            model_name='general',
            name='job',
            field=models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Job'),
        ),
    ]
