# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190125_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computerskills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(choices=[('', 'Сонгох'), ('office', 'MS OFFICE'), ('visio', 'MS VISIO'), ('access', 'MS ACCESS'), ('coraldraw', 'CORAL DRAW'), ('autocad', 'AUTOCAD')], default='Сонгох', max_length=16)),
                ('rate', models.CharField(choices=[('', 'Сонгох'), ('unacceptable', '1-Муу'), ('below_average', '2-Дундаас доош'), ('average', '3-Дунд'), ('above_average', '4-Сайн'), ('excellent', '5-Маш сайн')], default='Сонгох', max_length=16)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computerskills', to='application.General')),
            ],
            options={
                'db_table': 'computerskills',
            },
        ),
    ]
