# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_computerskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerskills',
            name='skill_name',
            field=models.CharField(choices=[('', 'Сонгох'), ('MSprodect', 'Микрософтын хэрэглээний программ'), ('adobe_pro', 'Adobe Pro'), ('photoshop', 'Photoshop'), ('autocad', 'Autocad'), ('sap', 'SAP'), ('rtbs', 'RTBS reporting'), ('msvisio', 'MS Visio'), ('msproject', 'MS Project'), ('indesign', 'Adobe Indesign'), ('coreldraw', 'Corel Draw')], default='Сонгох', max_length=16),
        ),
        migrations.AlterField(
            model_name='general',
            name='gender',
            field=models.CharField(choices=[('', 'Сонгох'), ('Male', 'Эрэгтэй'), ('Female', 'Эмэгтэй')], default='Сонгох', max_length=16),
        ),
    ]
