# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20190219_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otherskills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('rate', models.CharField(choices=[('', 'Сонгох'), ('unacceptable', '1-Муу'), ('below_average', '2-Дундаас доош'), ('average', '3-Дунд'), ('above_average', '4-Сайн'), ('excellent', '5-Маш сайн')], default='Сонгох', max_length=16)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otherskills', to='application.General')),
            ],
            options={
                'db_table': 'otherskills',
            },
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='education',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=160),
        ),
    ]
