# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20190220_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('', 'Сонгох'), ('huvi', 'Хувийн'), ('turees', 'Түрээсийн'), ('hamaatan', 'Хамаатаных')], default='Сонгох', max_length=25)),
                ('address', models.TextField()),
                ('phone1', models.TextField(max_length=10)),
                ('phone2', models.TextField(max_length=10)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Country')),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address1', to='application.General')),
            ],
        ),
        migrations.CreateModel(
            name='Address2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relitive', models.CharField(choices=[('', 'Сонгох'), ('wife', 'Эхнэр'), ('husband', 'Нөхөр'), ('son', 'Хүү'), ('daughter', 'Охин'), ('father', 'Эцэг'), ('mother', 'ЭХ'), ('brother', 'Ах'), ('sister', 'Эгч'), ('lilsis', 'Дүү'), ('father_law', 'Хадам аав'), ('mother_law', 'Хадам ээж'), ('ach', 'Ач'), ('zee', 'Зээ'), ('avga', 'Авга'), ('nagats', 'Нагац'), ('naiz', 'Найз'), ('busad', 'Бусад')], default='Сонгох', max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('phone1', models.TextField(max_length=10)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Country')),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address2', to='application.General')),
            ],
        ),
    ]
