# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_address1_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address1',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address1',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address1',
            name='general',
        ),
        migrations.RemoveField(
            model_name='address2',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address2',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address2',
            name='general',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='general',
            name='sap_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Address1',
        ),
        migrations.DeleteModel(
            name='Address2',
        ),
    ]
