# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_language'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='language',
            table='language',
        ),
    ]
