# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20190224_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilityofsport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofsport', models.CharField(max_length=60)),
                ('traingyears', models.CharField(max_length=10)),
                ('degreeandaward', models.CharField(max_length=250)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilityofsport', to='application.General')),
            ],
            options={
                'db_table': 'abilityofsport',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage', models.TextField()),
                ('disadvantage', models.TextField()),
                ('vision', models.TextField()),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantage', to='application.General')),
            ],
            options={
                'db_table': 'advantage',
            },
        ),
        migrations.CreateModel(
            name='Awardsandprize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=150)),
                ('awarded_year', models.DateField()),
                ('companyofaward', models.CharField(max_length=150)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardsandprize', to='application.General')),
            ],
            options={
                'db_table': 'awardsandprize',
            },
        ),
        migrations.CreateModel(
            name='Maritalstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fl_name', models.CharField(max_length=150)),
                ('relation', models.CharField(choices=[('', 'Сонгох'), ('wife', 'Эхнэр'), ('husband', 'Нөхөр'), ('son', 'Хүү'), ('daughter', 'Охин'), ('father', 'Эцэг'), ('mother', 'ЭХ'), ('brother', 'Ах'), ('sister', 'Эгч'), ('lilsis', 'Дүү'), ('father_law', 'Хадам аав'), ('mother_law', 'Хадам ээж'), ('ach', 'Ач'), ('zee', 'Зээ'), ('avga', 'Авга'), ('nagats', 'Нагац'), ('naiz', 'Найз'), ('busad', 'Бусад')], default='Сонгох', max_length=25)),
                ('dateofbirth', models.DateField()),
                ('current_position', models.CharField(max_length=150)),
                ('cellphone', models.CharField(max_length=10)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maritalstatus', to='application.General')),
            ],
            options={
                'db_table': 'maritalstatus',
            },
        ),
    ]
