# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_abilityofsport_advantage_awardsandprize_maritalstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youraddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofaddress', models.CharField(choices=[('', 'Сонгох'), ('huvi', 'Хувийн'), ('turees', 'Түрээсийн'), ('hamaatan', 'Хамаатаных')], default='Сонгох', max_length=25)),
                ('city', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=150)),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(max_length=10)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Country')),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youraddress', to='application.General')),
            ],
            options={
                'db_table': 'youraddress',
            },
        ),
    ]
