# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_youraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='email',
        ),
        migrations.RemoveField(
            model_name='general',
            name='sap_id',
        ),
    ]
