# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20190225_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilityofsport',
            name='degreeandaward',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='abilityofsport',
            name='traingyears',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='abilityofsport',
            name='typeofsport',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='advantage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='disadvantage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='awardsandprize',
            name='award_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='awardsandprize',
            name='awarded_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='awardsandprize',
            name='companyofaward',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='computerskills',
            name='rate',
            field=models.CharField(blank=True, choices=[('', 'Сонгох'), ('unacceptable', '1-Муу'), ('below_average', '2-Дундаас доош'), ('average', '3-Дунд'), ('above_average', '4-Сайн'), ('excellent', '5-Маш сайн')], default='Сонгох', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='computerskills',
            name='skill_name',
            field=models.CharField(blank=True, choices=[('', 'Сонгох'), ('MSprodect', 'Микрософтын хэрэглээний программ'), ('adobe_pro', 'Adobe Pro'), ('photoshop', 'Photoshop'), ('autocad', 'Autocad'), ('sap', 'SAP'), ('rtbs', 'RTBS reporting'), ('msvisio', 'MS Visio'), ('msproject', 'MS Project'), ('indesign', 'Adobe Indesign'), ('coreldraw', 'Corel Draw')], default='Сонгох', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, choices=[('', 'Сонгох'), ('burendund', 'Бүрэн дунд'), ('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('doctor', 'Доктор'), ('academich', 'Академич'), ('profeccor', 'Профессор')], default='Сонгох', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='languageknowledge',
            name='language_name',
            field=models.CharField(blank=True, choices=[('', 'Сонгох'), ('english', 'Англи хэл'), ('russian', 'Орос хэл'), ('chinesse', 'Хятад хэл'), ('korean', 'Солонгос хэл'), ('japanesse', 'Япон'), ('spanish', 'Испани'), ('other', 'Бусад')], default='Сонгох', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='languageknowledge',
            name='listening',
            field=models.CharField(blank=True, choices=[('', 'Сонгох'), ('unacceptable', '1-Муу'), ('below_average', '2-Дундаас доош'), ('average', '3-Дунд'), ('above_average', '4-Сайн'), ('excellent', '5-Маш сайн')], default='Сонгох', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='languageknowledge',
            name='reading',
            field=models.CharField(blank=True, choices=[('', 'Сонгох'), ('unacceptable', '1-Муу'), ('below_average', '2-Дундаас доош'), ('average', '3-Дунд'), ('above_average', '4-Сайн'), ('excellent', '5-Маш сайн')], default='Сонгох', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='languageknowledge',
            name='speaking',
            field=models.CharField(blank=True, choices=[('', 'Сонгох'), ('unacceptable', '1-Муу'), ('below_average', '2-Дундаас доош'), ('average', '3-Дунд'), ('above_average', '4-Сайн'), ('excellent', '5-Маш сайн')], default='Сонгох', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='languageknowledge',
            name='writing',
            field=models.CharField(blank=True, choices=[('', 'Сонгох'), ('unacceptable', '1-Муу'), ('below_average', '2-Дундаас доош'), ('average', '3-Дунд'), ('above_average', '4-Сайн'), ('excellent', '5-Маш сайн')], default='Сонгох', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='cellphone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='current_position',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='fl_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='relation',
            field=models.CharField(blank=True, choices=[('', 'Сонгох'), ('wife', 'Эхнэр'), ('husband', 'Нөхөр'), ('son', 'Хүү'), ('daughter', 'Охин'), ('father', 'Эцэг'), ('mother', 'ЭХ'), ('brother', 'Ах'), ('sister', 'Эгч'), ('lilsis', 'Дүү'), ('father_law', 'Хадам аав'), ('mother_law', 'Хадам ээж'), ('ach', 'Ач'), ('zee', 'Зээ'), ('avga', 'Авга'), ('nagats', 'Нагац'), ('naiz', 'Найз'), ('busad', 'Бусад')], default='Сонгох', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='otherskills',
            name='rate',
            field=models.CharField(blank=True, choices=[('', 'Сонгох'), ('unacceptable', '1-Муу'), ('below_average', '2-Дундаас доош'), ('average', '3-Дунд'), ('above_average', '4-Сайн'), ('excellent', '5-Маш сайн')], default='Сонгох', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='otherskills',
            name='skill_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='youraddress',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='youraddress',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='youraddress',
            name='phone1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='youraddress',
            name='phone2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='youraddress',
            name='typeofaddress',
            field=models.CharField(blank=True, choices=[('', 'Сонгох'), ('huvi', 'Хувийн'), ('turees', 'Түрээсийн'), ('hamaatan', 'Хамаатаных')], default='Сонгох', max_length=25, null=True),
        ),
    ]
