# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20190226_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('occupation', models.CharField(blank=True, max_length=60, null=True)),
                ('position', models.CharField(blank=True, max_length=60, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driverskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=60, null=True)),
                ('driving_years', models.CharField(blank=True, max_length=60, null=True)),
                ('pro_type', models.CharField(blank=True, max_length=60, null=True)),
                ('protype_years', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('relative', models.CharField(blank=True, choices=[('', 'Сонгох'), ('wife', 'Эхнэр'), ('husband', 'Нөхөр'), ('son', 'Хүү'), ('daughter', 'Охин'), ('father', 'Эцэг'), ('mother', 'ЭХ'), ('brother', 'Ах'), ('sister', 'Эгч'), ('lilsis', 'Дүү'), ('father_law', 'Хадам аав'), ('mother_law', 'Хадам ээж'), ('ach', 'Ач'), ('zee', 'Зээ'), ('avga', 'Авга'), ('nagats', 'Нагац'), ('naiz', 'Найз'), ('busad', 'Бусад')], default='Сонгох', max_length=25, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='otherskills',
            old_name='skill_name',
            new_name='dissertation',
        ),
        migrations.RemoveField(
            model_name='general',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='general',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='otherskills',
            name='rate',
        ),
        migrations.AddField(
            model_name='experience',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='work_task',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherskills',
            name='dissertation_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computerskills',
            name='rate',
            field=models.CharField(blank=True, choices=[('', 'Сонгох'), ('unacceptable', 'Анхан шат'), ('average', 'Хэрэглээний түвшин'), ('above_average', 'Бүрэн эзэмшсэн'), ('excellent', 'Мэргэжлийн түвшинд')], default='Сонгох', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='computerskills',
            name='skill_name',
            field=models.CharField(blank=True, choices=[('', 'Сонгох'), ('MSprodect', 'Микрософтын хэрэглээний программ'), ('adobe_pro', 'Adobe Pro'), ('photoshop', 'Photoshop'), ('autocad', 'Autocad'), ('sap', 'SAP'), ('rtbs', 'RTBS reporting'), ('msvisio', 'MS Visio'), ('msproject', 'MS Project'), ('indesign', 'Adobe Indesign'), ('coreldraw', 'Corel Draw'), ('other', 'Бусад')], default='Сонгох', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='job',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='youraddress',
            name='typeofaddress',
            field=models.CharField(blank=True, choices=[('', 'Сонгох'), ('huvi', 'Хувийн'), ('turees', 'Түрээсийн'), ('hamaatan', 'Хамаатан садан')], default='Сонгох', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='emergency_number',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_number', to='application.General'),
        ),
        migrations.AddField(
            model_name='driverskill',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driverskill', to='application.General'),
        ),
        migrations.AddField(
            model_name='discription',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discription', to='application.General'),
        ),
    ]
