# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20190228_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='experience',
            name='worked_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
