# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20190228_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='image',
            field=models.FileField(blank=True, default='avatar.png', null=True, upload_to='person/avatar/'),
        ),
        migrations.AlterModelTable(
            name='discription',
            table='discription',
        ),
        migrations.AlterModelTable(
            name='driverskill',
            table='driverskill',
        ),
        migrations.AlterModelTable(
            name='emergency_number',
            table='emergency_number',
        ),
    ]
