# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_auto_20190228_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youraddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Country'),
        ),
    ]
