# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-09 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('about', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drug_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drug_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=100)),
                ('other_side', models.CharField(max_length=100)),
                ('zaavar', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('factory', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('drug_catedory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Drug_category')),
            ],
        ),
        migrations.CreateModel(
            name='Drug_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('number', models.IntegerField()),
                ('recived_date', models.DateField(default=django.utils.timezone.now)),
                ('about', models.CharField(max_length=100)),
                ('drug_add', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Drug_add')),
            ],
        ),
        migrations.CreateModel(
            name='Drug_order_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='drug_order',
            name='drug_order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Drug_order_status'),
        ),
        migrations.AddField(
            model_name='drug_add',
            name='drug_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Drug_detail'),
        ),
    ]
