# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-09 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug_detail',
            name='nairlaga',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
