# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-09 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_department'),
        ('drug', '0002_drug_detail_nairlaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_important',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shirheg', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Drug_category')),
            ],
        ),
        migrations.CreateModel(
            name='Emchilgee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('costumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('disc', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User')),
            ],
        ),
        migrations.CreateModel(
            name='Onosh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('disc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Onosh_and_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc', models.CharField(max_length=200)),
                ('history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.History')),
                ('onosh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Onosh')),
            ],
        ),
        migrations.RemoveField(
            model_name='drug_add',
            name='drug_detail',
        ),
        migrations.RemoveField(
            model_name='drug_order',
            name='drug_add',
        ),
        migrations.AddField(
            model_name='drug_order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User'),
        ),
        migrations.DeleteModel(
            name='Drug_add',
        ),
        migrations.AddField(
            model_name='emchilgee',
            name='onosh_and_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Onosh_and_history'),
        ),
        migrations.AddField(
            model_name='drug_important',
            name='emchilgee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Emchilgee'),
        ),
    ]
