# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-09 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_department'),
        ('drug', '0003_auto_20190409_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onosh_and_history',
            name='history',
        ),
        migrations.RemoveField(
            model_name='onosh_and_history',
            name='onosh',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='doctor',
            new_name='costumer',
        ),
        migrations.RemoveField(
            model_name='emchilgee',
            name='onosh_and_history',
        ),
        migrations.AddField(
            model_name='onosh',
            name='costumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User'),
        ),
        migrations.AlterField(
            model_name='emchilgee',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Onosh_and_history',
        ),
    ]
